#!/usr/bin/env python
import sys
from bowcaster.servers import ConnectbackServer

def main(ip_address,port=None):
    if port:
        server=ConnectbackServer(ip_address,port=port)
    else:
        server=ConnectbackServer(ip_address)

    server.serve()
    server.wait()

if __name__ == "__main__":
    ip_address="0.0.0.0"
    port=None

    if len(sys.argv) > 1:
        ip_address=sys.argv[1]

    if len(sys.argv) > 2:
        port=sys.argv[2]

    main(ip_address,port=port)
